### ISSUE TITLE
Scrollbar on ruler div

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#10]
A scrollbar sometimes appears on the horizontal ruler div  
<img width="842" alt="screen shot 2017-03-03 at 7 28 49 pm" src="https://cloud.githubusercontent.com/assets/933148/23575939/fedf58d0-004b-11e7-9447-0e12ff8a1f8e.png">

**Comment by turner** [comment]
I think this is now gone.

**Comment by turner** [comment]
Closed with commit fef685e1
