### ISSUE TITLE
Ruler bar is sometimes not readable

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#107]
At some resolutions the ruler bar is hard or impossible to read, see screenshot for example
<img width="838" alt="screen shot 2017-05-05 at 10 37 31 am" src="https://cloud.githubusercontent.com/assets/933148/25757553/c61fe86a-317f-11e7-8d1e-3a6fb61640b6.png">

**Comment by jrobinso** [comment]
Here's another example
<img width="492" alt="screen shot 2017-06-18 at 11 35 44 am" src="https://user-images.githubusercontent.com/933148/27263258-84f3071a-541a-11e7-9808-9ecb92305247.png">

**Comment by jrobinso** [comment]
There are actually 2 issues,  (1) increment step can be too close so text is unreadable, and (2) X and Y axes can use different tick increments.   Since X and Y are always at the same resolution scale they should use the same tick increment.

**Comment by turner** [comment]
Closed with commit 8813ed61
