### ISSUE TITLE
Ruler track text is fuzzy on high DPI displays

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#11]
<img width="842" alt="screen shot 2017-03-03 at 7 28 49 pm" src="https://cloud.githubusercontent.com/assets/933148/23575944/133aec2c-004c-11e7-8caa-06bd3a73f893.png">

**Comment by turner** [comment]
Closed with commit b103bcbb

**Comment by jrobinso** [comment]
Still fuzzy for me.  Maybe this is a Canvas thing, but are there canvas setting for text that might help?  Or a different font?   This is not a problem in igv.js.


<img width="865" alt="screen shot 2017-03-05 at 3 00 23 pm" src="https://cloud.githubusercontent.com/assets/933148/23592363/94b3e3da-01b4-11e7-9ad6-c553ad2eca9f.png">

**Comment by turner** [comment]
Hmmm ... Text is very sharp on my display. Are you using an old monitor or old OS? Blurry text is indeed a known issue with Canvas. There is ways of try and achieve sharp text that I have not looked into yet: https://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by jrobinso** [comment]
A new iMac

**Comment by jrobinso** [comment]
Text is blurry on my high DPI devices (iMac, MacBook).   Its sharp on my
"old" Dell monitor.
