### ISSUE TITLE
Direct url bug

### ISSUE THREAD

**Issue by theaidenlab** [aidenlab/juicebox.js#114]
http://aidenlab.org/juicebox/?state=1%2C1%2C0%2C0%2C0%2C12.84853999367298%2CNONE&colorScale=1305&hicUrl=http%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Frpe1%2FDarrowHuntley-2015%2FdelXa-chrX-diploid.hic

Using these state links doesn't update the display name/url of the contact map (but map itself does load fine).

**Comment by turner** [comment]
Closed with commit 3cf61a98
