### ISSUE TITLE
Adding a track resets map pixel size to 1

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#121]
Adding a track resets pixelSize to 1 (apparently).  Steps to reproduce

1. load a map
2. zoom to 1kb,  then zoom some more to get a pixel size >> 1,  e.g. start from this locus 1:118,806,512-118,966,112 1:118,801,926-118,963,126
3. pixels are > 1 (see screenshot)
4. load a track,  pixel size is now 1  (see 2nd screenshot)
5. 
<img width="891" alt="screen shot 2017-06-04 at 4 09 33 pm" src="https://cloud.githubusercontent.com/assets/933148/26766165/c8ebecb4-4940-11e7-9991-c95544b57522.png">
<img width="900" alt="screen shot 2017-06-04 at 4 09 54 pm" src="https://cloud.githubusercontent.com/assets/933148/26766167/cf081974-4940-11e7-89b0-039f9dd1d92c.png">

**Comment by turner** [comment]
When I enter the above locus I get the following error
![screen shot 2017-07-03 at 3 34 18 pm](https://user-images.githubusercontent.com/87169/27805881-3c8bd9ba-6005-11e7-8780-10b2eda7c386.png)

**Comment by turner** [comment]
Fixed with commit 7f7d9b6f
