### ISSUE TITLE
Multiple juicebox.js windows in a page

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#124]
Does not seem to work:
https://theaidenlab.github.io/figures/index_nathan.html
https://github.com/theaidenlab/figures/blob/gh-pages/index_nathan.html

Is this a supported feature?

**Comment by jrobinso** [comment]
That's correct, you can have only 1 per page.

**Comment by jrobinso** [comment]
You can now have multiple instances in a page.
