### ISSUE TITLE
Ruler track weirdness

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#13]
See photo  
<img width="838" alt="screen shot 2017-03-04 at 1 33 23 pm" src="https://cloud.githubusercontent.com/assets/933148/23582463/56d4a872-00df-11e7-9b76-e5b6ac855d55.png">

**Comment by jrobinso** [comment]
This is not a critical track,  perhaps just setting a larger minimum space between ticks would be sufficient.

**Comment by turner** [comment]
Closed with b103bcbb
