### ISSUE TITLE
Panning drifts away from cursor when browser.goto(...) is called to zoom

### ISSUE THREAD

**Issue by turner** [aidenlab/juicebox.js#132]
There is repeatable bug in `browser.goto()`. 
- Load a contact-map for chr1.
- Enter locus `1:62,000,000-125,000,000 1:62,000,000-125,000,000`. The will call `browser.goto()`. The intent here is to zoom in around the center. 
- Pan around and notice the map drifts away from the cursor. 

For comparison zoom all the way out and use the resolution selection widget to zoom (which calls `browser.setZoom()`). Pan around and notice no drift.

**Comment by jrobinso** [comment]
@turner Is this a new bug or does it exist in version (tag) v1.0?

**Comment by turner** [comment]
The bug is present in v1.0.
