### ISSUE TITLE
When Loading MiniMap Changing the resolution and then changing it back to the Initial resolution results in a image that is closer to the desired figure

### ISSUE THREAD

**Issue by musianat** [aidenlab/juicebox.js#136]
Inital State
![intialstate](https://user-images.githubusercontent.com/18267744/27755707-15a4721c-5db7-11e7-8765-5a55bb139635.jpg)
Change resoltion
![changeresolution](https://user-images.githubusercontent.com/18267744/27755711-1cb91fe4-5db7-11e7-88b4-e019194fabe5.jpg)
Change back to initial resolution
![chagebacktoinitalresolution](https://user-images.githubusercontent.com/18267744/27755714-21093b9c-5db7-11e7-9107-bbcbf5e5088b.jpg)

I think when the map is initially loaded it is doing some kind of scaling that is resulting in the worse image. after adjusting the resolution the map looks much more like how the figure 2A should look.

**Comment by musianat** [comment]
figure 2A for reference
![image](https://user-images.githubusercontent.com/18267744/27755775-91b726ce-5db7-11e7-99fe-1dda8a5cecd9.png)

**Comment by jrobinso** [comment]
Hi, I'm not sure what this is.   A comment or bug report?   If you change the resolution you cannot get back to the original state.   The original state is a custom one (in general) between resolutions with a pixelSize != 1.   I sent instructions on how to set the initial state to what you want on the Erez mailing list.

**Comment by jrobinso** [comment]
We might need some additional tools to set this originally.   BTW this might not be the best forum for discussing the figures,  its a public forum for bug reports and discussion on the juicebox.js application.

**Comment by theaidenlab** [comment]
I think the underlying issue is that normalization may not working in these, unless you specifically re-select it

**Comment by jrobinso** [comment]
Verified that normalization is working by stepping through code.    I think the underlying issue is a pixel size of 2.415....  initially.

**Comment by jrobinso** [comment]
BTW initial normalization WILL NOT WORK unless you have changed your code to use the pattern demonstrated here:  http://igv.org/web/jb/test/fig2A-test.html
