### ISSUE TITLE
Changing resolutions can result in negative "x,y"  state

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#14]
See screenshot.    The "clamping logic" in shiftPixels probably needs to be applied.  
<img width="838" alt="screen shot 2017-03-04 at 1 38 50 pm" src="https://cloud.githubusercontent.com/assets/933148/23582491/258a7a66-00e0-11e7-93a3-618e203c7319.png">

**Comment by turner** [comment]
Yep. I need to do a proper zoom-about-locus-centroid. On it now.
