### ISSUE TITLE
ENCODE loader should handle "not found"

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#149]
The ENCODE loader hangs (spins forever) when selecting .hic files for genomes other than those supported by ENCODE.    The query to the ENCODE webservice returns a 404 in those cases.    This needs to be caught and handled better,  first by emptying the current table and ideally with a message to the user that no tracks are available.

An alternative to the 404 is to keep a list of supported genome ids and check before doing the query.    This is not ideal as the list of supported genomes might grow, but that's not likely.   The list includes at a minimum hg19, hg38, mm10, and probably mm9.   Consult the Encode website.

**Comment by jrobinso** [comment]
To reproduce the error load the first map in the contact list (Dudchenko et al...)

**Comment by turner** [comment]
An error dialog is now presented. Closed with commit f6419c80
