### ISSUE TITLE
Simple straw/dump function

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#150]
we are looking for is a very simple javascript wrapper/function similar to straw:
https://github.com/theaidenlab/straw

Something like
`straw <NONE/VC/VC_SQRT/KR> <hicFile> <chr1>[:x1:x2] <chr2>[:y1:y2] <BP/FRAG> <binsize>`
​which returns an array or matrix with the data​ for the specified region​.

**Comment by EmilyZiyiYe** [comment]
The ideal output is a sparse matrix which contains the contact records.

**Comment by jrobinso** [comment]
See https://github.com/igvteam/juicebox.js/blob/master/test/testStraw.js.

**Comment by smhsu** [comment]
#154 quality-of-life improvements
