### ISSUE TITLE
Unable to load local file

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#187]
I select a local file to load and nothing happens:
<img width="774" alt="screen shot 2017-10-16 at 2 56 40 pm" src="https://user-images.githubusercontent.com/6503789/31632455-98eb79de-b282-11e7-9bb3-80f502218095.png">
<img width="764" alt="screen shot 2017-10-16 at 2 57 05 pm" src="https://user-images.githubusercontent.com/6503789/31632463-9f0d4c84-b282-11e7-9fd4-71d8579ee882.png">

**Comment by jrobinso** [comment]
OK, this is a dependency on underscore in the site.js file.   I will look at removing underscore usage for this file,  alternatively we can include underscore in the index.html / juicebox-test.html files.  Thanks for catching this.

**Comment by jrobinso** [comment]
Fixed an pushed, it should auto build in ~5 minutes.
