### ISSUE TITLE
Load Encode table in background

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#196]
This is a performance enhancement -- start loading the Encode table model immediately on a genome change, rather than on showing the modal.    This will in most cases insure the widget is usable as soon as its opened.    

Some state variable will probably need set to indicate loading, so that if the modal is opened before its finished a spinny can be displayed until it is ready.

**Comment by turner** [comment]
Implemented. Closed with commit 9dcfa7fb
