### ISSUE TITLE
Resolution dropdown has different appearance in deployed html

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#20]
The resolution pulldown looks different in hic.html,  compared to the look in hic-dev.html.   See the picture below.   hic.html is the deployed app and will need kept up to date with changes affecting style. 

<img width="880" alt="screen shot 2017-03-05 at 12 24 10 pm" src="https://cloud.githubusercontent.com/assets/933148/23591030/dcea14a0-019e-11e7-8d36-86b92ed8204e.png">

**Comment by turner** [comment]
Not seeing this now. Closing issue.
