### ISSUE TITLE
Gear popup menu placement issue

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#213]
The menu is popping up well above the track in  examples/website/oath-dev.html.   Inspecting the css with developer tools reveals the popup is position rule is "relative".   Relative is quite difficult to control, it means relative to its normal position,  maybe absolute is better.  I would expect the single root of everything to be relative positioned, but everything inside to be absolute.

<img width="295" alt="screen shot 2017-11-26 at 4 57 23 pm" src="https://user-images.githubusercontent.com/933148/33250468-89ea9720-d2e5-11e7-9e7a-f9ef71fcdc08.png">

**Comment by turner** [comment]
This was fixed as a side effect of fixing the data-range panel placement bug. I was mistakenly using the y-axis track as the parent element. See commit 37563f30
