### ISSUE TITLE
With 3 maps,  synchronization failed

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#215]
Synchronization fails on the 3rd map when switching to All 

https://goo.gl/Rprg3P

**Comment by jrobinso** [comment]
This appears to be caused by chromosome case sensitivity, in particular ALL for the first 2 maps and All for the third.   Fixing issue #217 should fix this as well.

**Comment by helgathorv** [comment]
Note that the chromosome menu in the third map has "All" but the menus for the 1st and second map have "ALL".  If you select "All" in the third map, the first and second do not update.
