### ISSUE TITLE
Missing y tracks

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#225]
Where are the Y tracks in examples/figures/figure6-dev.html?

<img width="1211" alt="screen shot 2017-11-28 at 9 58 01 pm" src="https://user-images.githubusercontent.com/933148/33360162-6a97d9fc-d487-11e7-8fa4-b355930e7b19.png">

**Comment by turner** [comment]
Here is what I see. Run from master branch
![screen shot 2017-11-29 at 10 11 31 am](https://user-images.githubusercontent.com/87169/33382157-f4305fc0-d4ed-11e7-8e1e-87399c03827f.png)

**Comment by jrobinso** [comment]
Fixed
