### ISSUE TITLE
Resolution pulldown incorrect for "All" genome view

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#234]
The resolution for the "All-All" genome view is not correct,  it just shows the resolution you were at before you switched to that view.

The "All" resolution is specified in the hic file,  we can get it,  but unlike other chromosomes, there is a single value available.    We should probably switch the contents of the chromosome pulldown to reflect this value (no other resolutions available)  when in All-all view,  since the pulldown also acts as the resolution label.   This needs fixed for 1.0,   it should be easy,   we can add a field to the dataset "wholeGenomeResolution".

**Comment by jrobinso** [comment]
You can now get the whole genome resolution from  browser.dataset.wholeGenomeResolution.  This should be useful in fixing this issue,  specifically in  handling the "MapLoad" event of hicResolutionSelector.   One option is to have 2 pulldowns ready,  one for "all" and one for everything else.  Switch the one used in the "LocusChange" handling.

**Comment by turner** [comment]
Closed with commit b90ea73b
