### ISSUE TITLE
Panel de-selection issues

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#244]
Hey guys -

Happy holidays! I hope you guys have been having a wonderful time with your families! And I will follow up soon with Craig to hopefully get the final acceptance!

Separately, I noticed an annoying issue with jbox.js. It came up a bunch of times before but I never bothered to diagnose it carefully, but tonight I did.

Here it is: when a gadget stops 'thinking' and displays, the information about which gadget was selected, and the accompanying red border, is lost. 

This is extremely annoying in practice because of the following.

Often, I start with a single gadget and select a map. Then, while it is loading, I open a new gadget, open the menu, and start looking for another map I want. The trouble is, by the time I find the map I want for gadget #2, in the background gadget #1 has finished loading. 

So now instead of gadget #2 starting to load the map I picked, I get an error message saying: "ERROR: You must select a map panel by clicking the panel header."

And then I have to go through the motions of selecting gadget #2 and choosing my map for gadget #2 all over again.

(Interestingly, as the load times get faster, this issue has been getting worse! That's because the chance that a map has loaded before a second map has been chosen increase.)

Anyway, fixing this would eliminate 90% of the errors I encounter!

I might add, as a bonus, that if there are a few empty gadgets, and you select a contact map but no gadget is selected, it should know to place the map in one of the empty gadgets instead of throwing an error.

**Comment by jrobinso** [comment]
I think we should do 2 things.   (1) Don't de-select the map panel on load.   This is also annoying when loading tracks after the map load.    We thought this was a good idea at the time, doesn't work well in practice  (2) When loading a map,  if there is an empty panel select it rather than popup the message.  Will need to be careful here on the definition of empty if another map is loading.

**Comment by turner** [comment]
Closed with commit 573f2e90
