### ISSUE TITLE
Color scale control

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#25]
Implement color scale control as in desktop Juicebox.  This will control the property contactMatrixView.colorScale.  

        this.colorScale = new igv.GradientColorScale(
            {
                low: 0,
                lowR: 255,
                lowG: 255,
                lowB: 255,
                high: 2000,
                highR: 255,
                highG: 0,
                highB: 0
            }
        );

**Comment by turner** [comment]
Closed with commit b357c1af
