### ISSUE TITLE
The 2D tracks menu doesn't match the html

### ISSUE THREAD

**Issue by nchernia** [aidenlab/juicebox.js#252]
Loading from this file for the 2D tracks

https://hicfiles.s3.amazonaws.com/internal/tracksMenu_2D.hg19.txt

Look at the labels at the bottom (4DN).  What is displayed in the menu is different.

![image](https://user-images.githubusercontent.com/1417819/35571410-0e6979ca-05a0-11e8-96d7-475ce0517f3c.png)

**Comment by jrobinso** [comment]
The file is not correctly formatted, in particular some of the lines at the end are not tab delimited.  They are ignored.  

<img width="866" alt="screen shot 2018-01-30 at 8 25 13 pm" src="https://user-images.githubusercontent.com/933148/35605181-d6525140-05fb-11e8-8126-5c3bfc123572.png">
