### ISSUE TITLE
add local hic file error

### ISSUE THREAD

**Issue by lidaof** [aidenlab/juicebox.js#287]
Hi Jim,

Just want to try load a local .hic file at http://aidenlab.org/juicebox/, but get the following error:
![image](https://user-images.githubusercontent.com/102806/50848516-1b62c700-133a-11e9-8170-a232b01ef462.png)

can you check this please? Thanks.

**Comment by jrobinso** [comment]
Hi, yes by coincidence I discovered that myself yesterday.   I'll have a
fix out shortly.

**Comment by lidaof** [comment]
Thanks @jrobinso

**Comment by jrobinso** [comment]
I pushed a fix and let the aidenlab know.  Thanks for the report.
