### ISSUE TITLE
chromogram: draft vs hi-c improved assembly

### ISSUE THREAD

**Issue by ersgupta** [aidenlab/juicebox.js#307]
Hi, is there a script using which I make plot chromograms like in Fig1 of Dudchenko et al. 2017 to show a comparison from the old to improved assembly?

**Comment by dudcha** [comment]
Hello ersgupta.

This is a 3D-DNA script: https://github.com/theaidenlab/3d-dna/blob/master/supp/make-rainbow-tracks-assembly.sh

Olga

**Comment by ersgupta** [comment]
Hey Olga,
Thanks a lot. :)

Saurabh

**Comment by ersgupta** [comment]
Two points:
1. I get an error saying that I have annotations which span multiple contigs. I see that you have a *-w-split.awk to take care of this. However, this needs to be changed in one line in make-rainbow-tracks-assembly.sh. I made the respective change and the error goes away.
2. The output file contains same color (0,0,0) for all scaffolds. It seems this is not taken into account in the script.

**Comment by jrobinso** [comment]
Hi @ersgupta ,   this issue is not about juicebox.js,  @dudcha where is the proper forum for this?

**Comment by dudcha** [comment]
@ersgupta Please move this to 3D-DNA issue board or aidenlab.org/forum.html.

**Comment by ersgupta** [comment]
Hi @jrobinso sure. Will do. :)
