### ISSUE TITLE
Panning bug causes rendering to vanish/appear during pan

### ISSUE THREAD

**Issue by turner** [aidenlab/juicebox.js#33]
When view dataset GM12878 in-situ combined
https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/combined.hic

During pan, the rendering flickers on and off:
![juiceboxjs-panning-bug](https://cloud.githubusercontent.com/assets/87169/23665761/60a8712c-0327-11e7-84a1-8ee14116a8d2.gif)

**Comment by jrobinso** [comment]
Fixed
