### ISSUE TITLE
Load by URL leads to "unamed" dataset - regression

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#330]
Another juicebox.js regression.  If loading by URL,  the "name" of the dataset is "unnamed".   It should be the "file" part of the url, that is the bit after the last "/" and before the "?", if any.   Try loading  this for example, the name should be "GM12878_ultra_42B_1k.hic"
```
http://adam.3dg.io/suhas_juicebox/libs/GM12878_ultra/GM12878_ultra_42B_1k.hic
```

**Comment by turner** [comment]
Fixed with PR: https://github.com/igvteam/juicebox.js/pull/331
