### ISSUE TITLE
Axis Scrollbars

### ISSUE THREAD

**Issue by turner** [aidenlab/juicebox.js#34]
Implement x-axis and y-axis scrollbars:

![screen shot 2017-03-07 at 12 57 35 pm](https://cloud.githubusercontent.com/assets/87169/23671128/25beb358-0338-11e7-8f02-6d9c18f442a1.png)

**Comment by jrobinso** [comment]
This is a duplicate of #8

**Comment by turner** [comment]
yep. closing.
