### ISSUE TITLE
[Safari Bug]

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#344]
Also encountered by some chrome users apparently. I replicated this in Safari Version 14.0 on a Mac Book Pro.

Steps:
1. Click [https://tinyurl.com/y66hvj7z](https://tinyurl.com/y66hvj7z)
2. Go to `Load Tracks > ENCODE`
3. Clicking on any track does not appear to work

**Comment by jrobinso** [comment]
This is a known issue with Safari and is fixed, but aidenlab.org/juicebox is a bit out of date.   Safari can't handle the length of the ENCODE table,  it seems to have a limit of 50,000 rows.

**Comment by jrobinso** [comment]
Until aidenlab.org/juicebox is updated the only workaround is to not use Safari if you are loading ENCODE tracks.

WRT Chrome we haven't seen this, open a new issue for that with steps to reproduce.
