### ISSUE TITLE
Placement of color picker off when using multiple panels

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#347]
The placement of the foreground color picker for maps towards the right edge of the browser is well out of view when multiple panels are open.  Strangely the background color picker does not have this problem.   After finding and dragging the picker (not obvious, it looks like the click was ignored)  to a better location it is o.k. the next time.  It seems to remember the last position.

This is a bug because it looks and feels like nothing happened from the color map selector click.  Only if you notice a scrollbar appeared at the bottom of the browser do you know its there.

**Comment by turner** [comment]
Perhaps resolved earlier but this commit - a refactor from igv-ui - has correct positioning 9050557f
