### ISSUE TITLE
Load widget

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#35]
Widget for selecting the public datasets available in Juicebox desktop.    JB desktop uses a tree-folder metaphor.   **Note:  we don't have to use this metaphor, it could possibly be flattened as we did the Encode load widget for Cursor.**   The tree is defined in the following properties file

http://hicfiles.tc4ga.com/juicebox.properties

**_File description from casual inspection,  verify this might not be completely correct._**

The property keys are used as node ids.  The first 13 lines define a folder structure.   Remaining lines define hic file nodes.  Keys are ids but its not clear how they are used.   Values are comma delimited lists of 3 fields,  which appear to be

<folder id>   <menu label>  <hic file url>

**Comment by jrobinso** [comment]
Java code for parsing property file

```
for (String key : keys) {
           String value = properties.getProperty(key);
           DefaultMutableTreeNode node;
           final String[] values = value.split(",");
           if (values.length != 3 && values.length != 2) {
               JOptionPane.showMessageDialog(this, "Improperly formatted properties file; incorrect # of fields", "Error", JOptionPane.ERROR_MESSAGE);
               return false;
           }
           if (values.length == 2) {
               node = new DefaultMutableTreeNode(new ItemInfo(key, values[0], values[1]));
           } else {
               node = new DefaultMutableTreeNode(new ItemInfo(key, values[0], values[1], values[2]));
           }
           hashMap.put(key, node);
       }
       for (String key : keys) {
           DefaultMutableTreeNode node = hashMap.get(key);
           DefaultMutableTreeNode parent = hashMap.get(((ItemInfo) node.getUserObject()).parentKey);

           if (parent == null) {
               JOptionPane.showMessageDialog(this, "Improperly formatted properties file; unable to find parent menu "
                       + ((ItemInfo) hashMap.get(key).getUserObject()).parentKey + " for " +
                       key, "Error", JOptionPane.ERROR_MESSAGE);
               return false;
           } else {
               parent.add(node);
           }
       }
       return true;
   }
```

**Comment by sa501428** [comment]
we'll use @nchernia's branch, I'll delete mine

**Comment by jrobinso** [comment]
@sa501428 @nchernia  Comments?

**Comment by sa501428** [comment]
Let's leave the hardcoded links for tonight/tomorrow, I'll try to finish this on the weekend

**Comment by jrobinso** [comment]
Closing this as the load menu is not part of juicebox.js,  rather part of a specific page.
