### ISSUE TITLE
Offset is outside the bounds of the DataView Error

### ISSUE THREAD

**Issue by xzhuo** [aidenlab/juicebox.js#351]
Hi,
I got an error opening a hic file [https://wangftp.wustl.edu/~xzhuo/browser/HiC/panTro5.hic](https://wangftp.wustl.edu/~xzhuo/browser/HiC/panTro5.hic)

`RangeError: Offset is outside the bounds of the DataView`

I have no problem opening it with downloaded juicebox.

Can you help me with this?

Thanks!

**Comment by jrobinso** [comment]
Hi, this bug was fixed a long time ago, but the aidelab.org juicebox instance is out of date.  If you'd like you can load it at our instance at 

https://igv.org/juicebox

**Comment by xzhuo** [comment]
> Hi, this bug was fixed a long time ago, but the aidelab.org juicebox instance is out of date. If you'd like you can load it at our instance at
> 
> https://igv.org/juicebox

It works! Thank you for your swift reply!
