### ISSUE TITLE
Not able to load hic data in the web page

### ISSUE THREAD

**Issue by yancychy** [aidenlab/juicebox.js#353]
Hi, 
   I tried to load the hic to view in the web broswer https://aidenlab.org/juicebox/ by goole drive and URL from HPC. Both of them are failed.  Is there any thing wrong? Thanks. 
Google drive: 
Error loading https://drive.google.com/file/d/1DaQzOGDhDoeEfMWnMshLQMVuerI/view?usp=drive_web: 404 
URL:
Error loading https://hpc......../test.allValidPairs.hic: TypeError: Failed to fetch 
 
Best 
Yang

**Comment by jrobinso** [comment]
Could you try https://igv.org/juicebox and see if that works for you?  Please let us know.

**Comment by yancychy** [comment]
Ok Thanks. I tired to google drive and HPC links. Both of them are failed. I tried to load HPC links to WashU Genome browser, it is ok. But WashU genome browser only has 5kb resolution. I tried to load hic by Dropbox, it sucessed. But my dropbox has no extrac storage sapce.

**Comment by jrobinso** [comment]
I don't know what an "HPC" link is.  If you tried Google Drive from https://igv.org/juicebox and it doesn't work I don't have an answer for you.   If you share your file with Google user jrobinso (at) broadinstitute.org I will look at it.

**Comment by yancychy** [comment]
Thanks. HPC is the ftp server in our organization.  I have shared my data with jrobinso (at) broadinstitute.org at google drive.

**Comment by jrobinso** [comment]
I was able to load that file with no problem by URL from https://igv.org/juicebox (see screenshot below).    ftp:// protocol will not work for sure,  only https:// and http:// are supported

![Screen Shot 2021-02-08 at 7 43 39 AM](https://user-images.githubusercontent.com/933148/107243249-a9aa4b00-69e1-11eb-8c84-e356679fea93.png)

**Comment by jrobinso** [comment]
Another suggestion, if you are using Chrome try Firefox or Safari.

**Comment by yancychy** [comment]
Thanks. I tried different browsers and failed. My URL is https. The goole drive and URL are both failed. I will try other ways.

**Comment by yancychy** [comment]
I have successfully load the URL from our HPC cluster. But I have another question about how to use the panel. 
I can only load A and B hic files into same panel. When I click the "add Map panel", the new panel is empty. I cannot load any hic file into the new panel. 
https://drive.google.com/file/d/1rIyI2lj97vb3GV-UbgSf4qofeQ1igvFF/view?usp=sharing

**Comment by jrobinso** [comment]
You can, you have to select the panel (by clicking on it) you want to load
a new map into before using the "Load" function.

**Comment by yancychy** [comment]
Thanks. I can load it to new panel now.
