### ISSUE TITLE
Bug: 1D tracks and 2D map un-linked

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#354]
The 1D track and 2D heatmap are unlinked, and move at different rates relative to each other.

Link: [https://tinyurl.com/yagrxzev](https://tinyurl.com/yagrxzev) 
Move the map by dragging, and see how the 1D track position is untethered from the heatmap. 
Replicated in Opera and Chrome.

Video here: [https://www.dropbox.com/s/ubk54lu2guzbmp8/screen%20recording%202021-02-22%20at%203.14.59%20pm.mov?dl=0](https://www.dropbox.com/s/ubk54lu2guzbmp8/screen%20recording%202021-02-22%20at%203.14.59%20pm.mov?dl=0)

**Comment by jrobinso** [comment]
Strange, I can see the problem with the tinyURL you posted, but if I try to recreate the situation from scratch I can't.  See this url for example,  same tracks and location.  https://tinyurl.com/ycqp3684

**Comment by jrobinso** [comment]
OK,  I see it.   The link you sent has a map pixel size != 1 (it's  2), it must have been zoomed with the lock, or via some other means.   So the tracks are not accounting for the pixel size of the map when computing genomic location.   I have no idea how far back this bug goes, and am not interested in searching.    Can probably have a fix tomorrow sometime.
