### ISSUE TITLE
Asymmetric Track

### ISSUE THREAD

**Issue by AlyssaBlack** [aidenlab/juicebox.js#358]
Loop calls are not shown symmetrically across the diagonal: https://tinyurl.com/ybwhwxhj

**Comment by sa501428** [comment]
https://tinyurl.com/yfp88884
<img width="217" alt="Screen Shot 2021-04-06 at 4 30 14 PM" src="https://user-images.githubusercontent.com/6503789/113780945-8a841d00-96f5-11eb-8417-e846b62dad54.png">
