### ISSUE TITLE
Map not showing after session saved

### ISSUE THREAD

**Issue by dudcha** [aidenlab/juicebox.js#363]
Hi Jim, Doug,

I do not have a plausible explanation for this, but here's a link to a session I can't get to work:
https://www.dropbox.com/s/qqi4ulu7v5axkvg/Figure_S20_geo.json?dl=0

It will show either one map or all except that one. I wonder if this is an issue when the length of norm vector is different between different maps.

Thanks,
Olga

**Comment by dudcha** [comment]
P.S.: This persists in local json save or with link. Does not help if I remove the status or the nvi fields. -Olga

**Comment by jrobinso** [comment]
This is fixed.  The problem was all the maps had the same ID,  but different chromosome sizes.   The equal IDs fooled juicebox.js into thinking they were the same assembly, and it failed during synching.
