### ISSUE TITLE
wig.gz from GEO

### ISSUE THREAD

**Issue by dudcha** [aidenlab/juicebox.js#364]
Not a bug but an ask: GEO archives 1D tracks. While bed.gz seems to load fine this is not the case for wig.gz. Not sure if intended or easy to address. -Olga

**Comment by jrobinso** [comment]
Not intended.  Sorry I could probably do this but you can do it faster, can you send me a link to a geo wig.gz file?

**Comment by jrobinso** [comment]
Also, btw, if the wig.gz file (or bed.gz) is too large the browser will likely just hang.   There's really nothing we can do about that.

**Comment by dudcha** [comment]
Understood. I was just surprised to find out that bedpe.gz seemed to work, hence the inquiry.

Thanks,
Olga

**Comment by jrobinso** [comment]
If you send me a geo link to a wig.gz that's not working I'll investigate, there's no reason I can see it shouldn't work unless its just too large.

**Comment by dudcha** [comment]
Hey Jim,

Closing this as either I was doing something wrong before or what, but miraculously with 2.1.10 this also worked just fine..

Thanks again for all the fixes!
Olga
