### ISSUE TITLE
About Embedding juicebox.js

### ISSUE THREAD

**Issue by ChangliangWang** [aidenlab/juicebox.js#369]
Dear Jrobinso,

I am trying to embed juicebox.js into my database according to the tutorial at "https://igvteam.github.io/juicebox.js/docs/embedding". But I didn't find the 'dist/juicebox.min.js'. Could you give me the link to the file? Thanks very much for your help. 

Best Regards,
Changliang.

**Comment by jrobinso** [comment]
Apologies those instructions are incomplete, I will work on updating them today.   If you could give me an idea of what you are trying to do that would be helpful, and what environment you are using to build your webpage.   By that I mean are you using in frameworks, or plain javascript and html?

**Comment by jrobinso** [comment]
@ChangliangWang See the [README](https://github.com/igvteam/juicebox.js) for some updated info, and followup with additional questions here.   I would like to make this work for you.

**Comment by ChangliangWang** [comment]
Dear Jrobinso,

Sorry for the late reply. 
Now I am trying 'plain javascript and html'. I have read your updated README. Thanks very much for your help. 

Best Regards,
Changliang.

**Comment by jrobinso** [comment]
@ChangliangWang I just now pushed a few more updates to the README.   If you run into problems or have further questions don't hesitate to ask.   See especially the examples in the "examples" directory.

Note that if you are serving your hic files from a different host than your webpage you will have to enable "CORS" on the server with the hic files.   This is a general javascript / web requirement.  We have some general information about this [here](https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements#cross-origin-resource-sharing-cors), and there is lots more information on CORS on the web.

**Comment by ChangliangWang** [comment]
Dear Jim,

Thank you sooooo much for the detailed tutorial. I have embedded Juicebox.js into my database, successfully.

Have a nice day.

Best Regards,
Changliang.
