### ISSUE TITLE
Scrollbar wackiness

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#37]
If you load "GM12878" and select resolution "50",  then select resoution "500"  you'll see something like this.   This is repeatable,  zooming out from a lower resolution does this. 

![screen shot 2017-03-09 at 9 12 53 pm](https://cloud.githubusercontent.com/assets/933148/23783046/6c00af3e-050d-11e7-8271-e71a7935cbdb.png)

**Comment by turner** [comment]
I am testing this now. I can't reproduce. I zoom in/out out/in. navigate. Swap datasets. Looks fine.

**Comment by jrobinso** [comment]
Seen only intermittently, and not for some time,  so I'm closing.

**Comment by jrobinso** [comment]
Reopening,  I can reproduce this reliably now.  Load GM12878,  then select "1 22 refresh" from the chr selector.    
<img width="956" alt="screen shot 2017-03-22 at 5 02 10 pm" src="https://cloud.githubusercontent.com/assets/933148/24226062/844f695e-0f21-11e7-8637-2e3a7e54dc80.png">

**Comment by jrobinso** [comment]
This is what Juicebox Desktop does for chromosomes 1-22 zoomed fully out.  I think this is the right thing and what we should shoot for.    When the arithmetic is correct I think this will just happen
![Uploading Screen Shot 2017-03-22 at 5.29.37 PM.png…]()

**Comment by turner** [comment]
Closed with commit 27615892
