### ISSUE TITLE
ENCODE list

### ISSUE THREAD

**Issue by nchernia** [aidenlab/juicebox.js#378]
The ENCODE list doesn't seem up to date, there are no intact Hi-C maps listed; the 1D track list also doesn't seem up to date.

**Comment by jrobinso** [comment]
Both were updated about 2 weeks ago, can you give me the encode identifier for a specific map and track that are missing?

**Comment by nchernia** [comment]
Searching for "intact" returns nothing
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/1417819/201979740-9e7f5f91-ed6b-41d3-bd9e-85530e670535.png">

Looking for IMR-90 shows only in-situ and dilution
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/1417819/201979954-4ecf35d4-aedb-44df-9184-6c54c8a015c6.png">

Going to ENCODE, can see IMR-90 intact: https://www.encodeproject.org/experiments/ENCSR345VTI/

Can click "Juicebox" and "Visualize" and it works, just not listed in the ENCODE database.

**Comment by jrobinso** [comment]
@nchernia I will send you a link to the notebook that updates these tables

**Comment by jrobinso** [comment]
These should be up-to-date now
