### ISSUE TITLE
Assembly > Import Map Assembly Option

### ISSUE THREAD

**Issue by GallVp** [aidenlab/juicebox.js#386]
Hello

Thank you for sharing your useful toolbox. 

I am wondering if juicebox.js has an option similar to Assembly > Import Map Assembly option in the Juicebox desktop GUI app which can be used to add a .assembly file obtained from an AGP file using the agp2assembly.py script (https://github.com/phasegenomics/juicebox_scripts). The desired effect is a 2D annotation showing the assembled scaffolds as shown in the attached figure.

![Screenshot 2023-03-20 at 9 27 40 AM](https://user-images.githubusercontent.com/8924367/226207069-d0e59f3b-166c-4d62-a8f2-dffe87e68fd9.png)

Cheers
Usman R.

**Comment by jrobinso** [comment]
No it does not.  For 2D annotations the "bedpe" format is supported.  

Are you using juicebox.js as an embedded component, or loading from a juicebox-web instance (such as the one at aidenlabe.org/juicebox?

**Comment by GallVp** [comment]
Thank you.

I am using juicebox.js as an embedded component.

**Comment by jrobinso** [comment]
In that case you might configure a 2D track like this

```
            "tracks": [
                {
                    "url": "https://www.dropbox.com/s/d2in3505qbekzx0/merged_loops.bedpe?dl=0",
                    "name": "merged_loops.bedpe"
                }
            ]

```

**Comment by GallVp** [comment]
Thank you @jrobinso 

Do you know any tool which can convert AGP files to BEDPE?

**Comment by jrobinso** [comment]
I don't, @nchernia @sa501428 any ideas?   

Is the AGP format described somewhere?

**Comment by GallVp** [comment]
It is described here: https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/

**Comment by jrobinso** [comment]
The relationship between that and bedpe is not obvious,  some scripting will probably be involved.
