### ISSUE TITLE
Using juicebox.js behind a VPN

### ISSUE THREAD

**Issue by GallVp** [aidenlab/juicebox.js#387]
Hi Team

Thank you for your amazing work and replying to our previous queries.

We are using juicebox.js as part of a HTML report. When we try to view the report while sitting behind a VPN (for working from home our organisation uses VPN), the contact map does not load. In the browser console, we get a resource timeout error

https://t5dvc6kn3f.execute-api.us-east-1.amazonaws.com/dev/nvi/storage.powerplant.pfr.co.nz%2Fworkspace%2Fhrtjbs%2Ftemp_folder%2Fresults%2Fhic%2FRS324.hic

Is it because of https://t5dvc6kn3f.execute-api.us-east-1.amazonaws.com/dev/nvi/ proxy?

Is there a way to use the library without the proxy?

**Comment by jrobinso** [comment]
Hi, that is not a proxy, and a timeout should have no effect on juicebox.js (other than a console error message).    I will look into it, could you tell me what version of juicebox.js are you using?

**Comment by jrobinso** [comment]
I just pushed a release that does not call the "nvi" service,  release 2.4.2.

**Comment by GallVp** [comment]
I was using the latest version 2.4.1. Tried it with 2.4.2. Very similar result. 

The error is "Failed to load resource: The request timed out". The resource link is https://t5dvc6kn3f.execute-api.us-east-1.amazonaws.com/dev/nvi/storage.powerplant.pfr.co.nz%2Fworkspace%2Fhrauxr%2Fassembly_qc%2FResults%2Fhic%2Fhap1.hic

Thank you!

**Comment by jrobinso** [comment]
Apologies there were 2 calls to that service, second one has also been removed.  The version is 2.4.3

I still don't know why you have this error in the first place,  I have not been able to reproduce it.   But version 2.4.3 should definitely not be calling it.

**Comment by GallVp** [comment]
Thank you @jrobinso 

The problem has been fixed by v2.4.3.

The problem only occurred when we tried to access a file stored on one of our organisation's servers after connecting to it using a VPN.
