### ISSUE TITLE
2D annotations do not do 1/2

### ISSUE THREAD

**Issue by nchernia** [aidenlab/juicebox.js#389]
There's a button for having the 2D annotation on just one side of the diagonal (or just one box, not sure which). However it doesn't seem to do anything right now.

Steps to reproduce:
Load map, load 2D annotation (bedpe), go to hamburger -> 2D Annotations and click the gray box. Gray box becomes diagonal indicating that annotations should be on only one side of the diagonal but they do not.

**Comment by jrobinso** [comment]
I'm going to move this to juicebox.js since that is where it will be fixed.

**Comment by turner** [comment]
Candidate fix PR:
https://github.com/igvteam/juicebox.js/pull/390

**Comment by jrobinso** [comment]
@nchernia This is fixed in juicebox.js,  it will need a juicebox-web release to be visible at aidenlab.org.  That will follow in a few days, hopefully, we don't fully control that.
