### ISSUE TITLE
Wrong icon

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#39]
The little icon that appears on web tabs and bookmarks is the IGV one.  We need to change it to Juicebox.    
<img width="107" alt="screen shot 2017-03-10 at 9 13 01 pm" src="https://cloud.githubusercontent.com/assets/933148/23820845/7f1a926e-05d6-11e7-922d-cda2b8380d75.png">

**Comment by turner** [comment]
Close with commit 928f160b
