### ISSUE TITLE
Question about A/B map in juicebox.js web page

### ISSUE THREAD

**Issue by Miracle-Yao** [aidenlab/juicebox.js#391]
Hi everyone,

I have a question about A/B map in juicebox.js web page when loading "B map". I would like to know the meaning of A/B map means that the contact counts are taken logarithmically and then subtracted?  log2[(A map contact counts)/(B map contact counts)]? Or is there another explanation?

thanks.

**Comment by jrobinso** [comment]
A/B is the ratio of normalized A to B counts, where normalization is simply dividing by the average count over the entire map.

```
(A-count / A-average) / (B-count / B-average)
```

**Comment by Miracle-Yao** [comment]
Thanks very much.
