### ISSUE TITLE
Local file

### ISSUE THREAD

**Issue by GallVp** [aidenlab/juicebox.js#392]
Hi Team

Thank you for your excellent library and support.

Is it possible to load a local `hic` file. We have a pipeline which creates a html report and shows the hic file. It works file when loading from a https server. But, sometimes people want to examine the report on their desktop browser. 

Because we use relative path to access the `hic` file, `juicebox.js` complains that

Fetch API cannot load file:///Users/XXXXX/XXXX/assemblyqc/results/hic/FI1.hic due to access control checks.

Thank you!

**Comment by jrobinso** [comment]
Its not possible to reference local files by file path with juicebox.js,  or any javascript web application for that matter.
