### ISSUE TITLE
Click and drag zoom

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#40]
Implement Juicebox-desktop click-drag zoom, enabled by holding alt key down while clicking.    This is a very useful mode for zooming.    See slack video for demonstration.

Could we have a transparent canvas overlay on top of the canvas used to draw the heatmap?  Or some other element on top?  Probably similar to the "ruler" in igv.js,  but this one would be a rectangle with an anchor point (the initial alt-clock location).

Again see Slack for video.

**Comment by turner** [comment]
My sweep-zoom `dat_sweep_zoom` was beginning to drift from master so decided to rebase/merge with `master`. The functionality is commented out. See commit 1195119a

**Comment by jrobinso** [comment]
x,y coordinates after zooming should match x,y coordinates of swept area (in base coordinates).   When this is correct assign back to me and I'll deal with pixelSize so final zoomed region is exactly equal to swept region (again in base coordinates).
