### ISSUE TITLE
File Doesn't Load

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#51]
Maybe a hic file format version issue.

http://igv.org/web/jb/hic.html?state=1%2C1%2C0%2C0%2C0%2C8.024052224929061%2C2000&hicUrl=http%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fexternal%2Fli%2Fmcf7-rnapii-saturated.hic

**Comment by jrobinso** [comment]
Fixed
