### ISSUE TITLE
Production data load pulldown does not update

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#53]
There's a problem with the "production" dataset load menu (in hic.html).  When loading from a bookmark the pulldown is not updated to reflect the loaded dataset.   I've debugged the relevant code in site.js (below).   The query IS returning the correct $option object,  however the selection ("$option.prop('selected', true))  is not having any effect.   Perhaps this is because the pulldown is created using the "chosen" jQuery plugin.   Its not a requirement that we use that plugin,  I suggest we dump it and just use a standard "select" as in hic-dev.html.  

    function updateDatasetPulldown(dataset) {

        var selector = '#dataset_selector option[value="' + dataset.url + '"]',
            $option = $(selector);

        if ($option) $option.prop('selected', true);

    }

**Comment by nchernia** [comment]
This isn't essential (chosen) but it's a lot nicer from a UI perspective,
particularly for mobile users. I will look at it later today, it is
probably the syntax of selected.
