### ISSUE TITLE
Toolbar alignment looks a bit ragged

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#54]
Alignment between the locus box and other elements looks a bit ragged.  I tend to think the goto box should align with the other non-label control elements, and be the same height.  The other 3 controls could be taller if needed.

<img width="875" alt="screen shot 2017-03-21 at 10 40 23 pm" src="https://cloud.githubusercontent.com/assets/933148/24183798/9f695d98-0e87-11e7-9ecc-58c7bfa7aae5.png">

**Comment by turner** [comment]
Fixed with commit 605b3010
