### ISSUE TITLE
Label chromosome bars

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#63]
When viewing inter-chr maps  (e.g. 1 vs 2) its hard to tell which axis is which.    JB desktop handles this by labeling the scroll-bar widgets with the chromosome name (see screenshot).   We don't have to do this exactly but need some indication.

<img width="171" alt="screen shot 2017-03-22 at 1 22 04 pm" src="https://cloud.githubusercontent.com/assets/933148/24220680/7754cc9e-0f08-11e7-8016-073d0b0c759d.png">

**Comment by turner** [comment]
Closed with commit a4fa19d6
