### ISSUE TITLE
Aiden Lab site

### ISSUE THREAD

**Issue by sa501428** [aidenlab/juicebox.js#68]
Per Erez's request, we've also set up on the main site:
http://aidenlab.org/juicebox-on-the-web/

Lmk if the wording needs to be updated.

Also, does someone have an idea why the top x-axis covers some of the panels? Is it because of some bootstrap conflict?

**Comment by jrobinso** [comment]
Probably is related to a bootstrap style conflict of some kind.

**Comment by jrobinso** [comment]
Working on a hack solution,  stay tuned...

**Comment by jrobinso** [comment]
Better now,  still needs some style work but I think its o.k. for this
evening


​

**Comment by sa501428** [comment]
Thanks Jim!

**Comment by jrobinso** [comment]
You're welcome.   I really am off to bed now,  I did more testing and found
a few more minor problems (and fixed them).   It seems pretty robust to me
now except for some known chromosome "scrollbar" weirdness for
inter-chromosome views.  Doug's aware of this and will look at it tomorrow,
 fixes should automatically be reflected in your page.

Its a little rough around the edges but way better than typical academic
tools.

**Comment by nchernia** [comment]
Great. I'll probably update content today.
