### ISSUE TITLE
Chromosome and go box control not friendly for long chromosome names

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#74]
See screenshot.      This is from the dataset  "Dudchenko et al. | Science 2017 Aedes aegypti AaegL4".   We're probably going to need a 2-row toolbar to accommodate everything. 

<img width="690" alt="screen shot 2017-03-23 at 10 38 21 pm" src="https://cloud.githubusercontent.com/assets/933148/24281969/e1f88362-1019-11e7-95fe-ab20fb877c19.png">

**Comment by jrobinso** [comment]
Perhaps the chromosome controls can be laid out in a line  with the "go" box underneath,  this would give lots more horizontal space to both.   So it would look like

[Chromosomes:  <pulldown 1>  <pulldown 2>   Refresh widget ]
[location text box                                                                            ]

@nchernia @sa501428 Do you guys have comments?   Does Erez have a git id?

**Comment by jrobinso** [comment]
Or maybe we just live with this

**Comment by nchernia** [comment]
I want to live with it and move toward  my widget in the future. Esp since
more and more lab members are using this as mobile.
