### ISSUE TITLE
Link will not produce exact same color scale.

### ISSUE THREAD

**Issue by nchernia** [aidenlab/juicebox.js#77]
E.g. https://www.dropbox.com/s/xgyze51ahv500ko/Screenshot%202017-03-24%2013.44.21.png?dl=0

versus when you follow link: http://aidenlab.org/juicebox/?colorScale=2376.409321807417&hicUrl=http%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fassembly%2Faedes%2Fcombined.hic

**Comment by jrobinso** [comment]
Resolved.
