### ISSUE TITLE
Juicebox web broken

### ISSUE THREAD

**Issue by theaidenlab** [aidenlab/juicebox.js#81]
http://www.aidenlab.org/juicebox/

Load a map, nothing happens.  Chrome dev tools says:

analytics.js Failed to load resource: the server responded with a status of 404 (Not Found)
theme.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://hicfiles.s3.amazonaws.com/hiseq/assembly/aedes/combined.hic?someRandomSeed=0.ttvsgoo2ohp8gj92lhe8w7b9 Failed to load resource: the server responded with a status of 403 (Forbidden)
hic.js:980 Error: 403
    at handleError (igv-beta.js:17650)
    at XMLHttpRequest.xhr.onload (igv-beta.js:17609)

Map loads in Desktop Juicebox (no 403 error)

**Comment by jrobinso** [comment]
The 404 pages are for files reference on the webpage that don't exist.  These however are not serious.   The 403 error is Amazon rejecting the request.   This might require a change in bucket policy.

**Comment by jrobinso** [comment]
To be clear, these are aidenlab webpage errors not juicebox.js errors, so I'm going to close this issue.   We'll follow up on the webpage errors by email.
