### ISSUE TITLE
Layout issues with juicebox-test

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#88]
Multiple layout issues with juicebox-test.html (see screenshot).  Missing some css?

<img width="950" alt="screen shot 2017-04-23 at 4 29 50 pm" src="https://cloud.githubusercontent.com/assets/933148/25318391/394ad8a0-2842-11e7-831a-139cd31d84fe.png">

**Comment by turner** [comment]
Fixed with commit b6953270
