### ISSUE TITLE
Dataset selection pulldown

### ISSUE THREAD

**Issue by jrobinso** [aidenlab/juicebox.js#9]
Pulldown to select dataset (file).   This is outside the embeddable  object,  as in the igv.js examples.   For now it will have only 2 selections.  Labels and URLs below

Test file - intra nofrag
https://s3.amazonaws.com/igv.broadinstitute.org/data/hic/intra_nofrag_30.hic

GM12878 in-situ combined
https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/combined.hic

**Comment by jrobinso** [comment]
Note: ultimately we're going to want a hierarchical control working off the same XML file used by the desktop app (see screenshot).   
<img width="703" alt="screen shot 2017-03-03 at 7 51 16 pm" src="https://cloud.githubusercontent.com/assets/933148/23575926/61a4d932-004b-11e7-8bb3-9c37f37e6df3.png">

**Comment by turner** [comment]
I'll close this for now and later create one for the more extended uber dropdown.

Closed with 930adc0a
