### ISSUE TITLE
Out of memory crash. Google Chrome

### ISSUE THREAD

**Issue by turner** [aidenlab/juicebox.js#97]
We hit a 'Google Chrome ran out of memory' crash when zooming in on chromosome 5 with dnase-seq (hg19) and chipseq (hg19 and GCH38) h3k27ac loaded. I have never seen this sort of issue previously. It can be reproduced by clicking on the link below:

http://igv.org/web/jb/test/juicebox-test.html?state=5%2C5%2C9%2C31.794016058074906%2C33.28274454572832%2C23.841635592102318%2CNONE&colorScale=0.024998522394373418&hicUrl=https%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fgm12878%2Fin-situ%2Fcombined.hic

**Comment by jrobinso** [comment]
Problem is (was) pixel size was too large.  It shouldn't be possible to create this link anymore.
