### ISSUE TITLE
Long chromosome/scaffold names should display vertically

### ISSUE THREAD

**Issue by turner** [aidenlab/juicebox.js#98]
Long chromosome/scaffold names should display vertically, along the chromosome cartoon, not horizontally, cf for instance:
http://igv.org/web/jb/test/juicebox-test.html?state=1%2C1%2C0%2C0%2C0%2C5.680295107378883%2CNONE&colorScale=2376.409321807417&hicUrl=http%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fassembly%2Faedes%2Fcombined.hic

**Comment by jrobinso** [comment]
This is a broader issue than orientation,  chromosome names are not handled well on the horizontal access either.   It looks like there is room for a single character, so "chr1" would be long  
<img width="632" alt="screen shot 2017-05-07 at 11 03 40 pm" src="https://cloud.githubusercontent.com/assets/933148/25792177/d9956c84-3379-11e7-810e-af3d1a367060.png">

**Comment by turner** [comment]
Closed with commit fc4c06af
