### ISSUE TITLE
Strange white grid in the background in the heatmaps sometimes

### ISSUE THREAD

**Issue by turner** [aidenlab/juicebox.js#99]
There's a strange white grid in the background in the heatmaps sometimes, as though tiles of the contact map were not quite adjacent, see for instance:
http://igv.org/web/jb/test/juicebox-test.html?state=1%2C1%2C4%2C595.7727028972848%2C671.2782551152848%2C1.229355452891301%2CNONE&colorScale=173.1049761052135&hicUrl=https%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fgm12878%2Fin-situ%2Fcombined.hic

**Comment by jrobinso** [comment]
Another example
http://igv.org/web/jb/test/juicebox-test.html?state=1%2C1%2C6%2C6795.011464765298%2C6866.874100702887%2C2.172623265840204%2CKR&colorScale=38.31542960520282&hicUrl=https%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fgm12878%2Fin-situ%2Fcombined.hic&name=Rao%20and%20Huntley%20et%20al.%20%7C%20Cell%202014%20GM12878%20(human)%20in%20situ%20MboI%20primary%2Breplicate%20(4.9B)&nvi=54386046426%2C55860&tracks=https%3A%2F%2Fhicfiles.s3.amazonaws.com%2Fhiseq%2Fgm12878%2Fin-situ%2Fcombined_peaks_with_motifs.txt%7C

**Comment by jrobinso** [comment]
I think this has been fixed, long ago
